services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${API_CONTAINER_NAME}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: ${DB_CONTAINER_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    env_file:
      - .env
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql

volumes:
  db_data: