name: Books API Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging

    env:
      DB_ADAPTER: ${{ secrets.DB_ADAPTER }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
      MYSQL_DATABASE: ${{ secrets.DB_NAME }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_NAME: ${{ secrets.DB_NAME }}
      SERVER_HOSTNAME:  ${{ secrets.SERVER_HOSTNAME }}
      SERVER_PORT:  ${{ secrets.SERVER_PORT }}
      DB_CONTAINER_NAME: ${{ secrets.DB_CONTAINER_NAME }}
      API_CONTAINER_NAME: ${{ secrets.API_CONTAINER_NAME }}
      GOOSE_DRIVER: ${{ secrets.DB_ADAPTER }}
      GOOSE_DBSTRING: ${{ secrets.DB_USERNAME }}:${{ secrets.DB_PASSWORD }}@tcp(${{ secrets.DB_NAME }})/${{ secrets.DB_NAME }}

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Setup Golang Version
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.4'
    
    # Create .env file
    - name: Create .env file
      run: |
        echo "DB_ADAPTER=${DB_ADAPTER}" >> .env
        echo "DB_USERNAME=${DB_USERNAME}" >> .env
        echo "DB_PASSWORD=${DB_PASSWORD}" >> .env
        echo "MYSQL_ROOT_PASSWORD=${DB_PASSWORD}" >> .env
        echo "DB_HOST=${DB_HOST}" >> .env
        echo "DB_PORT=${DB_PORT}" >> .env
        echo "DB_NAME=${DB_NAME}" >> .env
        echo "SERVER_HOSTNAME=${SERVER_HOSTNAME}" >> .env
        echo "SERVER_PORT=${SERVER_PORT}" >> .env
        echo "DB_CONTAINER_NAME=${DB_CONTAINER_NAME}" >> .env
        echo "API_CONTAINER_NAME=${API_CONTAINER_NAME}" >> .env
        echo "GOOSE_DRIVER=${DB_ADAPTER}" >> .env
        echo "GOOSE_DBSTRING=${DB_USERNAME}:${DB_PASSWORD}@tcp(${DB_HOST}:${DB_PORT})/${DB_NAME}" >> .env
    
    # Build and Run the Docker Container
    - name: Build and Run Server
      run: |
        make up
  
    # Wait for a few seconds to ensure the Docker Container has started
    - name: Wait for container startup
      run: sleep 10

    # Copy the built artifacts from the Docker container to the GitHub Pages directory
    - name: Copy build artifacts
      run: |
        mkdir -p gh-pages
        CONTAINER_ID=$(docker ps --filter "name=${API_CONTAINER_NAME}" --format "{{.ID}}")
        docker cp "${CONTAINER_ID}":/app/docs/. ./gh-pages

    # Publish to GitHub Pages
    - name: Publish to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        publish_dir: ./gh-pages

    # Clean up Artifacts directory after Deployment on Github Pages
    - name: Clean up artifacts
      run: rm -rf ./gh-pages
